version: 2
jobs:
  sdk:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Build docker SDK image
          command: docker build -t apks -f docker/Dockerfile docker
  offroad:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Build docker SDK image
          command: docker build -t apks -f docker/Dockerfile docker
      - run:
          name: Build offroad
          command: docker run -v $PWD:/tmp/openpilot/apks --rm apks /bin/sh -c 'cd offroad && ./build.sh'
      - store_artifacts:
          name: Store offroad apk
          path: offroad/ai.comma.plus.offroad.apk
          destination: ai.comma.plus.offroad.apk

workflows:
  version: 2
  main:
    jobs:
      - sdk
      - offroad:
          requires:
            - sdk
